development: &default
  adapter: postgresql
  encoding: unicode
  database: instagram-authority-analyser-development
  pool: 5
  username: postgres
  password:
  host: localhost

test:
  <<: *default
  database: instagram-authority-analyser-test

production:
  <<: *default
  database: instagram-authority-analyser-production
